In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as mtp
import pandas as pd

In [2]:
data_set= pd.read_csv('Dataset.csv') 

In [3]:
x= data_set.iloc[:,:-1].values

In [4]:
y= data_set.iloc[:,3].values 

In [6]:
#Handling missing data (Replacing missing data with the mean value) 
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 22121.0]
 ['France' 35.0 58000.0]
 ['Spain' 23.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
# Encoding categorical data
# Encoding the Independent Variable

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],
remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)
print('\n')

# Encoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 22121.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 23.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


[0 1 0 0 1 1 0 1 0 1]


In [8]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=1) 
print(x_train)
print(x_test)
print(y_train)
print(y_test)
print('\n')

[[0.0 0.0 1.0 23.0 52000.0]
 [0.0 1.0 0.0 40.0 22121.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]




In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
st_x= StandardScaler() 
x_train= st_x.fit_transform(x_train)

In [12]:
x_test= st_x.transform(x_test)